# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true
	block_entities = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				villager = true
				zombie = true
				spider = true
				creeper = true
				skeleton = true
				item = true
				witch = true
				painting = true
				enderman = true
				bat = true
				cow = true
				pig = true
				armor_stand = true
				glow_squid = true
				iron_golem = true
				axolotl = true
				squid = true
				chicken = true
				zombie_villager = true
				cod = true
				salmon = true
				tropical_fish = true
				sheep = true
				arrow = true
				warden = true
				experience_orb = true
				wither = true
				wither_skull = true
				illusioner = true
				slime = true
				vindicator = true
				wolf = true
				fox = true
				wandering_trader = true
				pillager = true
				ravager = true
				phantom = true
				potion = true

			[light_sources.settings.entities.naturalist]
				bluejay = true
				bear = true
				snake = true
				finch = true
				lizard = true
				firefly = true
				butterfly = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true

			[light_sources.settings.entities.meadow]
				wooly_sheep = true

			[light_sources.settings.entities.pointblank]
				javelin_rocket = true
				at4_rocket = true
				smaw_rocket = true
				grenade40mm = true
				grenade = true
				grenade20mm = true

